### ISSUE TITLE
Final Full-stack project Kanban setup

### ISSUE THREAD

**Issue by Tracy-miranja** [Tracy-miranja/appoint-doctor-backend#7]
Hi reviewer,

In this full-stack capstone project, we are 5 collaborators. We successfully created the Kanban board according to the project requirement. [link](https://github.com/users/Tracy-miranja/projects/8).

These are the collaborators:
@TaiwoEnoch 
@Tracy-miranja 
@danutibe07 
@AbdusSattar-70 
@Lengushuru Charles

![image](https://github.com/Tracy-miranja/appoint-doctor-backend/assets/114406879/e8a11387-6a54-4695-b302-6d08faaa85ea)

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  
Good luck! 🎉 

## Highlights
- met all project requirements as far as I could see, good job 👍 
## Optional suggestions
- [OPTIONAL] Consider adding labels to your issues, it makes it easier to filter by different types and gives another added level of differentiation among tasks (front-end vs back-end etc.)
- [OPTIONAL] Ensure that you are adding realistic weight to your tasks.

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**Hope all is well, and that my comments were helpful. 😸**

Cheers and Happy coding!👏👏👏


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
